image: maven:3.8.4-jdk-8

services:
  - docker:dind

stages:
  - Deploy
# Deploy
deploy:
 stage: Deploy
 image: google/cloud-sdk
 script:
   - echo "$SERVICE_ACCOUNT_KEY" > key.json
   - gcloud auth activate-service-account --key-file=key.json
   - gcloud config set project devops-340313 
   - gcloud config set container/cluster cluster
   - gcloud config set compute/zone us-central1-c
   - gcloud container clusters get-credentials cluster --zone us-central1-c --project devops-340313 
   - kubectl apply -f manifests/produit.yaml
   - kubectl apply -f manifests/commande.yaml
   - kubectl apply -f manifests/paiement.yaml
   - kubectl apply -f manifests/clientui.yaml