apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientui-deployment
  labels:
    app: clientui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientui
  template:
    metadata:
      labels:
        app: clientui
    spec:
      containers:
      - name: clientui
        image: h4mz4/clientui
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clientui
spec:
  type: LoadBalancer
  selector:
    app: clientui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
