apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientui-deployment
  labels:
    app: clientui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clientui
  template:
    metadata:
      labels:
        app: clientui
    spec:
      containers:
      - name: clientui
        image: h4mz4/microservice-clientui
        ports:
        - containerPort: 8080
        env:
        - name: commande_url
          valueFrom:
            ConfigMapKeyRef:
              name: commande-config
              key: commande_url
        - name: produit_url
          valueFrom:
            ConfigMapKeyRef:
              name: produit-config
              key: produit_url
        - name: paiement_url
          valueFrom:
            ConfigMapKeyRef:
              name: paiement-config
              key: paiement_url
---
apiVersion: v1
kind: Service
metadata:
  name: clientui-service
spec:
  type: NodePort
  selector:
    app: clientui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100
