apiVersion: apps/v1
kind: Deployment
metadata:
  name: commande-deployment
  labels:
    app: commande
spec:
  replicas: 2
  selector:
    matchLabels:
      app: commande
  template:
    metadata:
      labels:
        app: commande
    spec:
      containers:
      - name: commande
        image: h4mz4/microservice-commandes
        ports:
        - containerPort: 9002
---
apiVersion: v1
kind: Service
metadata:
  name: commande
spec:
  selector:
    app: commande
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
