apiVersion: apps/v1
kind: Deployment
metadata:
  name: paiement-deployment
  labels:
    app: paiement
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paiement
  template:
    metadata:
      labels:
        app: paiement
    spec:
      containers:
      - name: paiement
        image: h4mz4/microservice-paiement
        ports:
        - containerPort: 9003
---
apiVersion: v1
kind: Service
metadata:
  name: paiement
spec:
  type: LoadBalancer
  selector:
    app: paiement
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
