apiVersion: apps/v1
kind: Deployment
metadata:
  name: produit-deployment
  labels:
    app: produit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: produit
  template:
    metadata:
      labels:
        app: produit
    spec:
      containers:
      - name: produit
        image: h4mz4/microservice-produits
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: produit
spec:
  type: LoadBalancer
  selector:
    app: produit
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
